<a target="_blank" href="https://colab.research.google.com/github/thinh-vu/vnstock/blob/main/docs/4_funds_vnstock3.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

## Khởi tạo đối tượng

In [ ]:
!pip install vnstock

In [1]:
# Gọi từ core module
from vnstock.explorer.fmarket.fund import Fund
fund = Fund()

# # Gọi từ Vnstock wrapper module - version 3.0.7
# from vnstock import Vnstock
# fund = Vnstock().fund()

Total number of funds currently listed on Fmarket:  52

## Liệt kê danh sách các quỹ

In [2]:
fund.listing().head()

Total number of funds currently listed on Fmarket:  52

,short_name,name,fund_type,fund_owner_name,management_fee,inception_date,nav,nav_change_previous,nav_change_last_year,nav_change_inception,...,nav_change_3m,nav_change_6m,nav_change_12m,nav_change_24m,nav_change_36m,nav_change_36m_annualized,nav_update_at,fund_id_fmarket,fund_code,vsd_fee_id
0,VCBF-MGF,QUỸ ĐẦU TƯ CỔ PHIẾU TĂNG TRƯỞNG VCBF,Quỹ cổ phiếu,CÔNG TY TNHH QUẢN LÝ QUỸ ĐẦU TƯ CHỨNG KHOÁN VI...,1.90,2021-10-28,13433.94,26.66,0.0,34.34,...,5.37,7.82,26.66,68.40,34.40,10.36,2025-01-01,46,VCBFMGF,VCBFMGFN001
1,SSISCA,QUỸ ĐẦU TƯ LỢI THẾ CẠNH TRANH BỀN VỮNG SSI,Quỹ cổ phiếu,CÔNG TY TNHH QUẢN LÝ QUỸ SSI,1.75,2014-09-25,40785.56,33.40,0.0,182.99,...,1.67,4.44,33.40,71.89,27.93,8.56,2025-01-01,11,SSISCA,SSISCAN001
2,PVBF,QUỸ ĐẦU TƯ TRÁI PHIẾU PVCOM,Quỹ trái phiếu,CÔNG TY CỔ PHẦN QUẢN LÝ QUỸ NGÂN HÀNG TMCP ĐẠI...,0.50,2020-02-06,14624.24,8.18,0.0,46.24,...,4.47,5.17,8.18,18.97,27.21,8.35,2025-01-01,45,PVBF,PVBFN001
3,VCBF-FIF,QUỸ ĐẦU TƯ TRÁI PHIẾU VCBF,Quỹ trái phiếu,CÔNG TY TNHH QUẢN LÝ QUỸ ĐẦU TƯ CHỨNG KHOÁN VI...,0.20,2019-08-08,14464.92,7.39,0.0,44.65,...,1.55,3.49,7.39,18.08,26.54,8.16,2025-01-01,33,VCBFFIF,VCBFFIFN001
4,VFF,QUỸ ĐẦU TƯ TRÁI PHIẾU BẢO THỊNH VINACAPITAL,Quỹ trái phiếu,CÔNG TY CỔ PHẦN QUẢN LÝ QUỸ VINACAPITAL,0.95,2013-03-31,23835.19,6.96,0.0,79.43,...,1.90,3.50,6.96,15.49,24.77,7.66,2025-01-01,21,VFF,VFFN003

## Tìm kiếm quỹ theo tên viết tắt

In [3]:
# Nhập 1 phần tên viết tắt để lọc
fund.filter('DC')

   id shortName
0  40     VNDCF
1  67      DCIP
2  62    HDBOND
3  27      DCBF
4  25      DCDE
5  28      DCDS
6  29      DCAF

## Thông tin chi tiết quỹ

### Tăng trưởng NAV

In [4]:
fund.details.nav_report('SSISCA')

Retrieving data for SSISCA

            date  nav_per_unit short_name
0     2017-01-04      14412.31     SSISCA
1     2017-01-11      14527.86     SSISCA
2     2017-01-18      14240.04     SSISCA
3     2017-01-25      14547.21     SSISCA
4     2017-01-31      14541.96     SSISCA
...          ...           ...        ...
1658  2024-12-25      40401.78     SSISCA
1659  2024-12-26      40904.88     SSISCA
1660  2024-12-27      40912.05     SSISCA
1661  2024-12-30      40927.49     SSISCA
1662  2024-12-31      40785.56     SSISCA

[1663 rows x 3 columns]

### Danh mục đầu tư lớn (top 10)

In [5]:
fund.details.top_holding('SSISCA')

Retrieving data for SSISCA

,stock_code,industry,net_asset_percent,type_asset,update_at,fundId,short_name
0,FPT,Công nghệ và thông tin,12.36,STOCK,2024-12-05,11,SSISCA
1,ACB,Ngân hàng,9.78,STOCK,2024-12-05,11,SSISCA
2,CTG,Ngân hàng,7.19,STOCK,2024-12-05,11,SSISCA
3,HPG,Vật liệu xây dựng,5.05,STOCK,2024-12-05,11,SSISCA
4,TCB,Ngân hàng,3.99,STOCK,2024-12-05,11,SSISCA
5,MBB,Ngân hàng,3.90,STOCK,2024-12-05,11,SSISCA
6,QNS,Thực phẩm - Đồ uống,3.84,STOCK,2024-12-05,11,SSISCA
7,VCB,Ngân hàng,3.84,STOCK,2024-12-05,11,SSISCA
8,MWG,Bán lẻ,3.52,STOCK,2024-12-05,11,SSISCA
9,STB,Ngân hàng,3.46,STOCK,2024-12-05,11,SSISCA

### Phân bổ theo ngành (Top 10)

In [6]:
fund.details.industry_holding('SSISCA')

Retrieving data for SSISCA

                      industry  net_asset_percent short_name
0                    Ngân hàng              32.16     SSISCA
1       Công nghệ và thông tin              12.36     SSISCA
2                 Bất động sản              11.67     SSISCA
3          Thực phẩm - Đồ uống               5.31     SSISCA
4            Vật liệu xây dựng               5.05     SSISCA
5             Sản xuất Phụ trợ               3.65     SSISCA
6                       Bán lẻ               3.52     SSISCA
7            Vận tải - Kho bãi               3.48     SSISCA
8                     Tiện ích               3.12     SSISCA
9                Thiết bị điện               3.03     SSISCA
10  Sản xuất Thiết bị, máy móc               2.83     SSISCA
11      Sản xuất Hàng gia dụng               2.60     SSISCA
12           Chế biến thủy sản               1.78     SSISCA
13    Sản xuất Nhựa - Hóa chất               1.62     SSISCA
14                 Chứng khoán               1.21     SSISCA
15           Chăm sóc sức khỏe               0.84     SSISCA

### Phân bổ theo tài sản

In [7]:
fund.details.asset_holding('SSISCA')

Retrieving data for SSISCA

   asset_percent                asset_type short_name
0           94.2                  Cổ phiếu     SSISCA
1            5.8  Tiền và tương đương tiền     SSISCA